### ISSUE TITLE
Please split up repository

### ISSUE THREAD

**Issue by tarsius** [VladimirAlexiev/emacs#1]
Since the contained libraries are not related, please consider creating a separate repository for each of them. This is useful for users who install packages by cloning repositories (instead of using `package.el`) and do not want to use all of those libraries. Thanks!

**Comment by tarsius** [comment]
Friendly ping!

**Comment by VladimirAlexiev** [comment]
thanks!

**Comment by tarsius** [comment]
Thank you!
